drupalai.settings:
  type: config_object
  label: 'Drupal AI settings'
  mapping:
    drupalai:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Drupal AI generator page title:'
        source_text:
          type: text
          label: 'Source text for lorem ipsum generation:'
block.settings.drupalai_block:
  type: block_settings
  label: 'Drupal AI block'
  mapping:
    drupal_ai_block_settings:
      type: text
      label: 'Drupal AI block settings'